library/urls.py
from django.urls import path
from .views import HomepageView, BookDetailView, UserProfileView, DepositMoneyView, BorrowingView

app_name = 'library'

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
    path('category/<str:category_slug>/', HomepageView.as_view(), name='category_wise_book'),
    path('user_profile/', UserProfileView.as_view(), name='user_profile'),
    path('deposit_money/', DepositMoneyView.as_view(), name='deposit_money'),
    path('book_detail/<int:id>/', BookDetailView.as_view(), name='book_detail'),
    path('borrowing_book/<int:id>/', BorrowingView.as_view(), name='borrowing'),
]

main_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('library.urls', namespace='library'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/models.py
from django.db import models
from django.contrib.auth.models import User


########## Category Model ##########
class Category(models.Model):
    category = models.CharField(max_length=50)
    def __str__(self):
        return f"{self.category}"


########## Book Model ##########
class Book(models.Model):
    book_img = models.ImageField(upload_to = 'library/media/upload/')
    book_title = models.CharField(max_length=100)
    book_description = models.TextField()
    book_borrowing_price = models.IntegerField(blank=True, null=True)
    book_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.book_title} | {self.book_borrowing_price}"


########## Borrow Model ##########
class Borrow(models.Model):
    book_id = models.IntegerField()
    username = models.CharField(max_length=50)
    borrowing_on = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.username} | {self.book_id}"


########## Review Model ##########
class Review(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"User: {self.user.username}   |||   Book: {self.book.book_title}"

library/forms.py
from django import forms
from authentication.models import UserAccount
from .models import Review

class DepositForm(forms.Form):
    balance = forms.DecimalField(
        widget=forms.NumberInput(attrs={
            'placeholder': 'Please enter the amount',
        })
    )


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['comment']

library/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.template.context_processors import request
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from authentication.models import UserAccount
from .models import Book, Borrow, Review, Category
from .forms import DepositForm, ReviewForm

########## Home Page View ##########
class HomepageView(View):
    def get(self, request, category_slug = None):
        data = Book.objects.all()
        categories = Category.objects.all()
        if category_slug is not None:
            category = Category.objects.get(category = category_slug)
            data = Book.objects.filter(book_category = category)
            return render(request, 'library/homepage.html', {'data': data, 'categories': categories})
        return render(request, 'library/homepage.html', {'data': data, 'categories': categories})


########## Book Detail View ##########
class BookDetailView(DetailView):
    model = Book
    pk_url_kwarg = 'id'
    template_name = 'library/book_detail.html'

    def post(self, request, id, *args, **kwargs):
        book = self.get_object()
        review_form = ReviewForm(data=request.POST)

        # Borrowed user can only write review
        borrowed = Borrow.objects.filter(username=request.user.username, book_id=book.id).exists()
        if borrowed:
            if review_form.is_valid():
                new_review = review_form.save(commit=False)
                new_review.book = book
                new_review.user = request.user
                new_review.save()
                messages.success(request, "Review Posted Successfully!")
                return redirect('library:book_detail', id=book.id)
        else:
            messages.warning(request, "You can only review books that you have borrowed!")
            return redirect('library:book_detail', id=book.id)
        context = self.get_context_data(review_form=review_form)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        review_form = kwargs.get('review_form', ReviewForm())

        context['review_form'] = review_form
        context['reviews'] = self.object.reviews.all()
        return context


########## User Profile View ##########
class UserProfileView(LoginRequiredMixin, View):
    template_name = 'library/user_profile.html'

    def get(self, request, *args, **kwargs):
        user_account = UserAccount.objects.get(user=request.user)

        user_borrows = Borrow.objects.filter(username=request.user.username)

        borrow_records = []
        for borrow in user_borrows:
            book = Book.objects.get(id=borrow.book_id)
            borrow_records.append({
                'borrow_id': borrow.id,
                'book_title': book.book_title,
                'book_borrowing_price': book.book_borrowing_price,
                'borrowing_on': borrow.borrowing_on
            })

        context = {
            'user': request.user,
            'balance': user_account.balance,
            'borrow_records': borrow_records
        }

        return render(request, self.template_name, context)


########## Money Deposit View ##########
class DepositMoneyView(View):
    model = UserAccount
    form_class = DepositForm
    template_name = 'library/deposit_money.html'
    success_url = '/user_profile/'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['balance']
            user_account = self.model.objects.get(user=request.user)
            user_account.balance += amount
            user_account.save()
            messages.success(request, f'Successfully deposited {amount}')

            # Email Send
            mail_subject = 'Money Deposit Successful!'
            message = render_to_string('library/email/deposit.html', {
                'user' : request.user,
                'amount' : amount,
                'balance' : user_account.balance
            })
            sent_email = request.user.email
            send_mess = EmailMultiAlternatives(mail_subject, '', to=[sent_email])
            send_mess.attach_alternative(message, 'text/html')
            send_mess.send()

            return redirect(self.success_url)
        return render(request, self.template_name, {'form': form})


########## Borrowing Book View ##########
class BorrowingView(View):
    model = Borrow
    success_url = '/user_profile/'

    def get(self, request, *args, **kwargs):
        return redirect('library:homepage')

    def post(self, request, id, *args, **kwargs):
        # book_id = request.POST.get('book_id')
        print(id)
        book_id = id
        if book_id:
            book = Book.objects.get(id=book_id)
            user_account = UserAccount.objects.get(user=request.user)
            if user_account.balance >= book.book_borrowing_price:
                user_account.balance -= book.book_borrowing_price
                user_account.save()
                print('Borrowed')
                Borrow.objects.create(book_id=book.id, username=request.user.username)
                messages.success(request, 'Book borrowed successfully')

                # Email Send
                mail_subject = 'Book Borrowing Successful!'
                message = render_to_string('library/email/borrow.html', {
                    'user': request.user,
                    'book': book,
                    'balance': user_account.balance
                })
                sent_email = request.user.email
                send_mess = EmailMultiAlternatives(mail_subject, '', to=[sent_email])
                send_mess.attach_alternative(message, 'text/html')
                send_mess.send()

                return redirect(self.success_url)
            else:
                messages.warning(request, 'Insufficient balance to borrow this book')
                return redirect('library:book_detail', id=book_id)

        messages.error(request, 'Failed to borrow book')
        return redirect('library:homepage')

library/templates/library/book_detail.html
{% extends 'base.html' %} {%load crispy_forms_tags %} {% block title %}
<title>Book Detail</title> {% endblock %} {% block content %}

<!--Book Detail-->
<section class="d-flex m-5 justify-content-evenly align-items-center">
  <div style="max-width: 50%">
    <img
      src="{{book.book_img.url}}"
      style="height: 80vh"
      class="card-img-top"
      alt="..."
    />
  </div>
  <div style="max-width: 50%">
    <h5 class="mb-3">{{book.book_title}}</h5>
    <p class="card-text">{{book.book_description}}</p>
    <p class="card-text">
      <strong>Borrowing Price:</strong> {{book.book_borrowing_price}}
    </p>
    <p class="card-text text-center">
      <small class="text-body-secondary">{{book.book_category}}</small>
    </p>
    {% if request.user.is_authenticated %}
    <form method="post" action="{% url 'library:borrowing' book.id %}">
      {% csrf_token %}
      <button style="width: 100%" class="btn btn-warning px-5">
        Borrow Now
      </button>
    </form>
    {% endif %}
  </div>
</section>

<section>
  <h1 class="text-center">Reviews</h1>
  <!--Review Form-->
  <form
    method="post"
    style="width: 50%; margin: auto"
    class="border border p-5 shadow-lg rounded-2 my-5"
  >
    {% csrf_token %}
    <h1 class="text-center mb-3">Add Your Review!</h1>
    {{review_form | crispy}}
    <input
      type="submit"
      value="Submit Comment"
      style="width: 100%"
      class="btn btn-outline-warning"
    />
  </form>

  <!--All Reviews-->
  <div
    style="width: 50%; margin: auto"
    class="border border p-5 shadow-lg rounded-2 my-5"
  >
    <h5 class="mb-3">Total Reviews: {{reviews | length}}</h5>
    {% for review in reviews %}
    <div class="card my-3">
      <div class="card-body">
        <div style="display: flex; justify-content: space-between">
          <p><strong>{{review.user.username}}</strong></p>
          <p><small>{{review.created_at}}</small></p>
        </div>
        <p>{{review.comment}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock %}

library/templates/library/deposit_money.html
{% extends 'base.html' %} {% load crispy_forms_tags %}

<!--Title-->
{% block title %} <title>Deposit Money</title> {% endblock %}

<!--Content-->
{% block content %}

<form method="post" style="width: 50%; margin: auto" class="mt-5">
  {% csrf_token %} {{ form | crispy }}
  <button type="submit" style="width: 100%" class="btn btn-primary btn-sm">
    Deposit
  </button>
</form>

{% endblock %}

library/templates/library/homepage.html
{% extends 'base.html' %}

<!--Title-->
{% block title %} <title>Home Page</title> {% endblock %}

<!--Content-->
{% block content %}

<section class="d-flex mt-5">
  <!--Filter by Category-->
  <div class="mx-5">
    <h3>Filter:</h3>
    <div class="form-check">
      <p class="form-check-label">
        <a href="{% url 'library:homepage' %}" style="text-decoration: none"
          >All Categories</a
        >
      </p>
    </div>
    {% for category in categories %}
    <div class="form-check">
      <p class="form-check-label">
        <a
          href="{% url 'library:category_wise_book' category.category %}"
          style="text-decoration: none"
          >{{category.category}}</a
        >
      </p>
    </div>
    {% endfor %}
  </div>

  <div class="d-flex flex-wrap justify-content-center gap-5 mb-5">
    {% for book in data %}
    <div class="card" style="width: 18rem">
      <img
        src="{{ book.book_img.url }}"
        style="height: 400px"
        class="card-img-top"
        alt="{{book.book_img.url}}"
      />
      <div class="card-body">
        <h5 class="card-title">{{book.book_title}}</h5>
        <p class="card-text">
          <strong>Borrowing Price:</strong> {{book.book_borrowing_price}}
        </p>
        <p class="card-text">
          <strong>Category:</strong> {{book.book_category}}
        </p>
        <a href="{% url 'library:book_detail' book.id %}" class="card-link"
          >View Details</a
        >
      </div>
    </div>
    {% endfor %}
  </div>
</section>
{% endblock %}

library/templates/library/user_profile.html
{% extends 'base.html' %}

<!--Title-->
{% block title %} <title>Profile</title> {% endblock %}

<!--Content-->
{% block content %}

<h1 class="text-center my-5">Hello, {{ user.first_name }}</h1>

<!--  Borrow Record-->
<div class="container mt-4">
  <div class="d-flex justify-content-between my-3">
    <h3 class="text-center">Your Borrowing Record</h3>
    <h3>Your Current Balance: {{balance}}</h3>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Borrowing ID</th>
        <th>Book Title</th>
        <th>Borrowing Price</th>
        <th>Borrowed On</th>
      </tr>
    </thead>
    <tbody>
      {% for record in borrow_records %}
      <tr>
        <td>{{ record.borrow_id }}</td>
        <td>{{ record.book_title }}</td>
        <td>{{ record.book_borrowing_price }}</td>
        <td>{{ record.borrowing_on }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="4" class="text-center">No books borrowed yet.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}