library/urls.py
from django.urls import path
from .views import HomepageView, BookDetailView, UserProfileView, DepositMoneyView, BorrowingView

app_name = 'library'

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
    path('category/<str:category_slug>/', HomepageView.as_view(), name='category_wise_book'),
    path('user_profile/', UserProfileView.as_view(), name='user_profile'),
    path('deposit_money/', DepositMoneyView.as_view(), name='deposit_money'),
    path('book_detail/<int:id>/', BookDetailView.as_view(), name='book_detail'),
    path('borrowing_book/<int:id>/', BorrowingView.as_view(), name='borrowing'),
]

main_project/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('library.urls', namespace='library'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    Title Block-->
    {% block title %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
<!--  Navbar-->
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'library:homepage' %}">Assignment - 5</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'library:homepage' %}">Home</a>
        </li>
      </ul>
      <div class="d-flex">
        {% if request.user.is_authenticated %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'library:user_profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'library:deposit_money' %}">Add Money</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
        {% else %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
</nav>


<!--Messages-->
{% if messages %}
    {% for mess in messages %}
        <div style="width: 75%; margin: auto" class="alert alert-{{mess.tags}} alert-dismissible fade show mt-3" role="alert">
            <strong>{{mess}}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}


<!--Content Block-->
{% block content %}
{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>